
export const START_PROCESS = 'START_PROCESS';

export const GET_ENDPOINT = 'GET_ENDPOINT';
export const GET_ENDPOINT_SUCCESS = 'GET_ENDPOINT_SUCCESS';
export const GET_ENDPOINT_FAILED = 'GET_ENDPOINT_FAILED';

export const GET_TOKEN = 'GET_TOKEN';
export const GET_TOKEN_SUCCESS = 'GET_TOKEN_SUCCESS';
export const GET_TOKEN_FAILED = 'GET_TOKEN_FAILED';

export const PROCESS_SUCCESS = 'PROCESS_SUCCESS';
export const PROCESS_FAILED = 'PROCESS_FAILED';